version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: ./client
      dockerfile: dockerfile
    volumes:
     - ./client:./app
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true